name: python-bootcamp-bsai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter
  - jupyterlab
  - notebook
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - pillow>=10.0.0
  - ipywidgets
  - ipykernel
  - pip
  - pip:
    - seaborn>=0.12.0
    - plotly>=5.15.0
